### ISSUE TITLE
What is "number of flips"?

### ISSUE THREAD

**Issue by cubicgate** [criteo-research/reco-gym#9]
Could you explain the meaning of "number of flips"?

    Thanks!

**Comment by ihtiihti** [comment]
When the Number of Flips is '0', there is a direct correlation between views and a product click.
However, when we increase that number, we introduce a particular distortion in that correlation, and the behaviour of the environment becomes not so straight forward.

There is the only one place where that Number of Flips is used: https://github.com/criteo-research/reco-gym/blob/494d0755c24304c216689f05f2e8f8edb74f44e4/recogym/envs/reco_env_v1.py#L119.
